/**
 * Scrape the live JOB PORTAL GLOBAL 2 store into a clean markdown source of
 * truth (knowledge/store-scrape.md).
 *
 * The same content is rendered into knowledge/PDFs/store-content.pdf and is
 * loaded at boot by src/knowledge/loader.js so the bot can answer from it.
 *
 * Usage: node scripts/scrape-store.js
 * No runtime dependencies — uses global fetch (Node >= 18).
 */

const fs = require('fs');
const path = require('path');

const HOME_URL = 'https://job-portal-global-2.myshopify.com/';
// Product URLs are read from the curated knowledge base so the handles stay
// in sync with what the bot already knows.
const { JOBS } = require('../src/knowledge/base');

const OUT_FILE = path.join(__dirname, '..', 'knowledge', 'store-scrape.md');

// --- HTML → text helpers -------------------------------------------------

/** Decode the common HTML entities into plain text. */
function decodeEntities(text) {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, ' ');
}

/** Strip tags and collapse whitespace. */
function stripTags(html) {
  return decodeEntities(html)
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Extract the <title> text, if present. */
function extractTitle(html) {
  const m = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  return m ? stripTags(m[1]) : '';
}

/**
 * Extract the meaningful text of the page: the <main>/<article> content when
 * available (Dawn uses <main id="MainContent">), falling back to <body>.
 * Returns an array of cleaned text chunks.
 */
function extractContent(html) {
  let scope = html.match(/<main[\s\S]*?<\/main>/i) || html.match(/<body[\s\S]*?<\/body>/i);
  const body = scope ? scope[0] : html;

  // Headings (h1–h6) become section markers.
  const parts = [];
  const re = /<h([1-6])[^>]*>([\s\S]*?)<\/h\1>/gi;
  let last = 0;
  let m;
  while ((m = re.exec(body)) !== null) {
    const between = stripTags(body.slice(last, m.index));
    if (between) parts.push(between);
    parts.push(`[H${m[1]}] ${stripTags(m[2])}`);
    last = m.index + m[0].length;
  }
  const tail = stripTags(body.slice(last));
  if (tail) parts.push(tail);

  return parts.filter(Boolean);
}

// --- Fetch + scrape ------------------------------------------------------

async function fetchPage(url) {
  const res = await fetch(url, {
    headers: { 'user-agent': 'Mozilla/5.0 (compatible; JobPortalBot/1.0)' },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return res.text();
}

async function scrapePage(url, label) {
  const html = await fetchPage(url);
  const title = extractTitle(html);
  const chunks = extractContent(html);
  const lines = [`## ${label}`, `Source: ${url}`, ''];
  if (title && !title.includes('404')) lines.push(`Title: ${title}`, '');
  lines.push(chunks.join('\n\n'));
  return lines.join('\n');
}

async function main() {
  const out = [];
  out.push('# Job Portal Global 2 — Store Content', '');
  out.push('> Auto-generated by scripts/scrape-store.js from the live storefront.', '');
  out.push(`> Generated: ${new Date().toISOString()}`, '');
  out.push('', '---', '');

  const failed = [];

  // Homepage.
  try {
    out.push(await scrapePage(HOME_URL, 'Homepage'));
    out.push('', '---', '');
  } catch (err) {
    failed.push(`${HOME_URL}: ${err.message}`);
  }

  // One section per job category.
  for (const job of JOBS) {
    try {
      out.push(await scrapePage(job.url, `${job.name} (${job.id})`));
      out.push('', '---', '');
    } catch (err) {
      failed.push(`${job.url}: ${err.message}`);
    }
  }

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, out.join('\n'), 'utf8');

  console.log(`Wrote ${OUT_FILE}`);
  console.log(`  Homepage: ${HOME_URL}`);
  console.log(`  Jobs: ${JOBS.length}`);
  if (failed.length) {
    console.warn(`  WARNING — ${failed.length} page(s) failed and were skipped:`);
    for (const f of failed) console.warn(`    - ${f}`);
  } else {
    console.log('  All pages scraped successfully.');
  }
}

main().catch((err) => {
  console.error('Scrape failed:', err);
  process.exit(1);
});
